version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cheftoo-mysql-prod
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PROD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_PROD}
      MYSQL_USER: ${MYSQL_USER_PROD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
    volumes:
      - /data/mysql:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: cheftoo-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../   # Spring 루트 경로 기준
      dockerfile: Dockerfile
    container_name: cheftoo-backend-prod
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cheftoo-mysql-prod:3306/${MYSQL_DATABASE_PROD}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER_PROD}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD_PROD}
      SPRING_REDIS_HOST: cheftoo-redis-prod
      SPRING_REDIS_PORT: 6379
    networks:
      - cheftoo-net-prod

networks:
  cheftoo-net-prod:
