name: Deploy Backend (Blue-Green)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Determine Active Stack
        id: check_stack
        run: |
          STACK=$(ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cat /home/ubuntu/current-stack.txt")
          if [ "$STACK" == "blue" ]; then
            echo "target_stack=green" >> $GITHUB_OUTPUT
          else
            echo "target_stack=blue" >> $GITHUB_OUTPUT
          fi

      - name: Set TARGET_STACK
        run: echo "Deploying to ${{ steps.check_stack.outputs.target_stack }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }}
               
          export KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}"
          export KAKAO_CLIENT_SECRET="${{ secrets.KAKAO_CLIENT_SECRET }}"
          export KAKAO_REDIRECT_URL="${{ secrets.KAKAO_REDIRECT_URL }}"
          export KAKAO_ACCESS_TOKEN_URL="${{ secrets.KAKAO_ACCESS_TOKEN_URL }}"
          export KAKAO_LOGIN_URL="${{ secrets.KAKAO_LOGIN_URL }}"
          export IMAGE_RECIPE_IMAGE_PATH="${{ secrets.IMAGE_RECIPE_IMAGE_PATH }}"
          export IMAGE_COOKINGORDER_IMAGE_PATH="${{ secrets.IMAGE_COOKINGORDER_IMAGE_PATH }}"
          export SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
          export SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
          export SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          export SPRING_REDIS_HOST="${{ secrets.SPRING_REDIS_HOST }}"
          export SPRING_REDIS_PORT="${{ secrets.SPRING_REDIS_PORT }}"
          export CLOUD_AWS_CREDENTIALS_ACCESS_KEY="${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}"
          export CLOUD_AWS_CREDENTIALS_SECRET_KEY="${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}"
          export CLOUD_AWS_S3_RECIPE_IMAGE_BUCKET="${{ secrets.CLOUD_AWS_S3_RECIPE_IMAGE_BUCKET }}"
          export CLOUD_AWS_S3_COOKINGORDER_IMAGE_BUCKET="${{ secrets.CLOUD_AWS_S3_COOKINGORDER_IMAGE_BUCKET }}"
          export SPRING_DATASOURCE_YOUTUBE_API_KEY="${{ secrets.SPRING_DATASOURCE_YOUTUBE_API_KEY }}"
          export SPRING_DATASOURCE_YOUTUBE_API_URL="${{ secrets.SPRING_DATASOURCE_YOUTUBE_API_URL }}"
               
          cd ${{ secrets.SERVER_PATH_BE }}
          git pull origin main
          docker-compose -f docker/docker-compose.${{ steps.check_stack.outputs.target_stack }}.yml up -d backend-${{ steps.check_stack.outputs.target_stack }}
#          echo "${{ steps.check_stack.outputs.target_stack }}" > /home/ubuntu/current-stack.txt
          EOF
