name: Deploy to Dev Environment

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Configure Spring Profile for Dev
        run: |
          cp src/main/resources/application-dev.properties src/main/resources/application.properties

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:dev

      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying dev branch to development environment..."
            docker compose pull backend-dev
            echo "Development deployment complete."