name: Deploy Backend (Blue-Green)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Determine Active Stack
        id: check_stack
        run: |
          STACK=$(ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cat /home/ubuntu/current-stack.txt")
          if [ "$STACK" == "blue" ]; then
            echo "target_stack=green" >> $GITHUB_OUTPUT
          else
            echo "target_stack=blue" >> $GITHUB_OUTPUT
          fi

      - name: Set TARGET_STACK
        run: echo "Deploying to ${{ steps.check_stack.outputs.target_stack }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }}
          cd ${{ secrets.SERVER_PATH_BE }}
          git pull origin main
          docker-compose -f docker/docker-compose.${{ steps.check_stack.outputs.target_stack }}.yml up -d backend-${{ steps.check_stack.outputs.target_stack }}
          echo "${{ steps.check_stack.outputs.target_stack }}" > /home/ubuntu/current-stack.txt
          EOF
