name: Deploy to EC2 on Main Push

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create application.properties file from secret
        run: |
          mkdir -p app-config
          echo "${{ secrets.APP_PROD_PROPERTIES }}" > app-config/application.properties

      - name: Copy application.properties to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: app-config/application.properties
          target: ${{ SERVER_PATH_BE_RESOURCES }}

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH_BE }}
            git pull origin main
            cd docker/
            docker compose -f docker/docker-compose-prod.yml down
            docker compose -f docker/docker-compose-prod.yml up -d --build
