name: Deploy Backend (Blue-Green)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Spring Profile for Prod
        run: |
          cp src/main/resources/application-prod.properties src/main/resources/application.properties

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Determine Active Stack
        id: check_stack
        run: |
          STACK=$(ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cat /home/ubuntu/current-stack.txt")
          if [ "$STACK" == "blue" ]; then
            echo "target_stack=green" >> "$GITHUB_OUTPUT"
          else
            echo "target_stack=blue" >> "$GITHUB_OUTPUT"
          fi

      - name: Set TARGET_STACK
        run: echo "Deploying to ${{ steps.check_stack.outputs.target_stack }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheftoo-backend:${{ steps.check_stack.outputs.target_stack }}

      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker compose pull backend-${{ steps.check_stack.outputs.target_stack }}
